wl-ime-type(1)

# NAME

wl-ime-type - type text via a Wayland IME

# SYNOPSIS

*wl-ime-type* [options...] <text>

# DESCRIPTION

wl-ime-type inserts text in a Wayland client via the input-method-unstable-v2
protocol extension.

# OPTIONS

*-h*
	Show help message.

# AUTHORS

Maintained by Simon Ser <contact@emersion.fr>, who is assisted by other
open-source contributors. For more information about wl-ime-type development,
see <https://git.sr.ht/~emersion.wl-ime-type>.
