# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "wayland-0.5.0-dev-lQa1ki3YAQCEdP63PCLFnVQzfXAixkrXsPavlEl8UkPe";
    path = fetchgit {
      url = "https://codeberg.org/ifreund/zig-wayland.git";
      rev = "52b54b71f1665b1b7ba61bf71a9319726e618fb6";
      hash = "sha256-BFjwEMhvDesYo8vvBMuNuUoiFgt3n+Q0ode4eHun+m4=";
    };
  }
]
